### PR TITLE
implement new API app-config.json

### LINKED ISSUE #246: Connection Error
Hi,
since Wednesday, 31.7.2024, there was an API change at WienerNetze. In the "main.xxxxxxxxxx.js" file the API Key after "b2cApiKey" cant't be found anymore. 

This error is shown in Homeassistant:
"custom_components.wnsm.api.errors.SmartmeterConnectionError: Could not obtain API Key - no match"

### PR DESCRIPTION
**Pull request by reox**
may fix #246 and #247 

Please check if it works for you as well!

### CODE REVIEW

**Comment by reox** [comment]
ah of course - someone has to fix the tests now 😅

**Comment by papedo79** [comment]
worked for me. Thanks!

**Review by papedo79 — APPROVED** [review]

**Comment by adamnet01** [comment]
Hi,  how to add these fixes? Copy to wnsm directory and restart homeassistant?

**Comment by papedo79** [comment]
> Hi, how to add these fixes? Copy to wnsm directory and restart homeassistant?

i changed the code lines as stated in files changed, saved and restarted homeassistant

**Comment by wceleda** [comment]
changed the codes lines as mentioned for client.py and constant.py but nothing has changed, no new data since 31.7.24

**Comment by tschoerk** [comment]
> changed the codes lines as mentioned for client.py and constant.py but nothing has changed, no new data since 31.7.24

Did you restart home assistant after the code changes? Only then it uses the updated files.

**Comment by wceleda** [comment]
> > changed the codes lines as mentioned for client.py and constant.py but nothing has changed, no new data since 31.7.24
> 
> Did you restart home assistant after the code changes? Only then it uses the updated files.

yes

**Comment by wceleda** [comment]
put API_CONFIG_URL = "https://smartmeter-web.wienernetze.at/assets/app-config.json" in old constants.py and restarted ha and now data ist displayed.

**Comment by slettmayer** [comment]
That change fixed https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/issues/246 and https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/issues/247 for me.
Thanks ❤️

**Comment by akicker** [comment]
implemented new API app-config.json and its working again :-)

**Comment by gotaede** [comment]
Fixed it for me.

**Review by tschoerk — APPROVED** [review]
Important bugfix to make the plugin useable again. Looks good!

**Comment by reox** [comment]
thanks @tschoerk for fixing the tests!

**Comment by DarwinsBuddy** [comment]
thank you so much for taking care. I was on vacation and couldn't look into it. :heart:

**Pull request merged**
